# Generated by Django 4.1.3 on 2023-01-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='Номер группы')),
                ('size', models.PositiveIntegerField(verbose_name='Кол-во учеников')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость чел.')),
                ('appointment', models.CharField(choices=[('Seminars', 'Семинар'), ('Lectures', 'Лекция'), ('Laboratory', 'Лаборатория'), ('Terminal', 'Терминал')], max_length=15, verbose_name='Тип ауд.')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_day', models.IntegerField()),
                ('break_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Seminars', 'Семинар'), ('Lectures', 'Лекция')], max_length=15)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('is_free', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAppointedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Seminars', 'Семинар'), ('Lectures', 'Лекция'), ('Terminal', 'Терминал')], max_length=15)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.subject')),
            ],
            options={
                'unique_together': {('subject', 'group', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.IntegerField()),
                ('week_day', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.group')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='timetable.room')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='timetable.subjectappointedgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='timetable.teacher')),
            ],
            options={
                'unique_together': {('subject', 'group', 'lesson', 'week_day')},
            },
        ),
    ]
